"""Alert definitions and data structures with Wazuh 0-16 levels and Active Response."""

import hashlib
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional
from src.evaluator.engine import DetectionResult
from src.alerting.active_response import ActiveResponseAction, ActiveResponseEngine


def _stable_alert_id(rule_id: str, event: Dict[str, Any], evidence: Dict[str, Any]) -> str:
    """Deterministic ``ALT-XXXXXXXX`` id for a (rule, event) detection.

    Re-processing the same event under the same rule yields the same id, so the
    V2 pipeline's dedup (spool + alert file) recognises a replayed/recovered
    alert instead of emitting it twice. Falls back to a random id only when the
    event carries nothing stable to key on.
    """
    parts = [
        str(rule_id),
        str(event.get("event_id") or event.get("event", {}).get("id") or ""),
        str(event.get("host_id") or ""),
        str(event.get("timestamp") or ""),
    ]
    if not any(parts[1:]):
        # nothing stable about this event -> keep V1's random behaviour
        parts.append(uuid.uuid4().hex)
    else:
        parts.append(",".join(sorted(str(k) for k in (evidence or {}))))
    digest = hashlib.sha1("|".join(parts).encode("utf-8")).hexdigest()
    return "ALT-" + digest[:8].upper()


@dataclass
class Alert:
    """Represents a standardized detection alert generated by the engine."""
    alert_id: str
    rule_id: str
    title: str
    description: str
    level: int  # Wazuh 0-16 Level
    severity: str
    confidence: float
    host_id: str
    timestamp: str
    event_id: Optional[str]
    evidence: Dict[str, Any]
    active_response: Optional[Dict[str, Any]] = None
    mitre_tactic: Optional[str] = None
    mitre_technique: Optional[str] = None
    compliance: List[str] = field(default_factory=list)
    tags: List[str] = field(default_factory=list)

    @classmethod
    def from_detection_result(cls, result: DetectionResult) -> "Alert":
        rule = result.rule
        event = result.event
        
        mitre_tactic = rule.mitre.tactic if rule.mitre else None
        mitre_technique = rule.mitre.technique if rule.mitre else None

        # Resolve automated Active Response action
        ar_action = ActiveResponseEngine.resolve_action(
            level=rule.level,
            event=event,
            custom_action=rule.active_response,
            reason=f"Rule [{rule.id}] triggered at Level {rule.level}",
        )

        return cls(
            alert_id=_stable_alert_id(rule.id, event, result.matched_evidence),
            rule_id=rule.id,
            title=rule.name,
            description=rule.description,
            level=rule.level,
            severity=rule.severity.value if hasattr(rule.severity, "value") else str(rule.severity),
            confidence=rule.confidence,
            host_id=event.get("host_id", "UNKNOWN_HOST"),
            timestamp=event.get("timestamp", datetime.utcnow().isoformat() + "Z"),
            event_id=event.get("event_id"),
            evidence=result.matched_evidence,
            active_response=ar_action.to_dict() if ar_action else None,
            mitre_tactic=mitre_tactic,
            mitre_technique=mitre_technique,
            compliance=rule.compliance,
            tags=rule.tags,
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
